"""add rich weather fields

Revision ID: 1d49c87af68a
Revises: ac6b6b7d7a7e
Create Date: 2026-09-09 20:23:15.665731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d49c87af68a'
down_revision: Union[str, Sequence[str], None] = 'ac6b6b7d7a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_forecasts', sa.Column('uv_index_max', sa.Float(), nullable=True))
    op.add_column('weather_forecasts', sa.Column('sunrise', sa.String(), nullable=True))
    op.add_column('weather_forecasts', sa.Column('sunset', sa.String(), nullable=True))
    op.add_column('weather_readings', sa.Column('apparent_temperature_c', sa.Float(), nullable=True))
    op.add_column('weather_readings', sa.Column('pressure_hpa', sa.Float(), nullable=True))
    op.add_column('weather_readings', sa.Column('dew_point_c', sa.Float(), nullable=True))
    op.add_column('weather_readings', sa.Column('hourly', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_readings', 'hourly')
    op.drop_column('weather_readings', 'dew_point_c')
    op.drop_column('weather_readings', 'pressure_hpa')
    op.drop_column('weather_readings', 'apparent_temperature_c')
    op.drop_column('weather_forecasts', 'sunset')
    op.drop_column('weather_forecasts', 'sunrise')
    op.drop_column('weather_forecasts', 'uv_index_max')
    # ### end Alembic commands ###
