"""create weather_forecasts table

Revision ID: 8cf329ef2553
Revises: 31e68d890247
Create Date: 2026-09-07 07:58:10.232238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cf329ef2553'
down_revision: Union[str, Sequence[str], None] = '31e68d890247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('forecast_date', sa.String(), nullable=False),
    sa.Column('weather_code', sa.Integer(), nullable=False),
    sa.Column('temp_max_c', sa.Float(), nullable=False),
    sa.Column('temp_min_c', sa.Float(), nullable=False),
    sa.Column('precip_probability_pct', sa.Float(), nullable=True),
    sa.Column('precip_sum_mm', sa.Float(), nullable=False),
    sa.Column('wind_speed_max_kmh', sa.Float(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('latitude', 'longitude', 'forecast_date', name='uq_weather_forecasts_lat_lon_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_forecasts')
    # ### end Alembic commands ###
