"""add historical_weather_readings table

Revision ID: ac6b6b7d7a7e
Revises: cbf59942506f
Create Date: 2026-09-08 16:24:06.970959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac6b6b7d7a7e'
down_revision: Union[str, Sequence[str], None] = 'cbf59942506f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_weather_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('observation_date', sa.String(), nullable=False),
    sa.Column('temp_2m_c', sa.Float(), nullable=True),
    sa.Column('dewpoint_2m_c', sa.Float(), nullable=True),
    sa.Column('precip_mm', sa.Float(), nullable=True),
    sa.Column('wind_speed_10m_kmh', sa.Float(), nullable=True),
    sa.Column('wind_direction_10m_deg', sa.Float(), nullable=True),
    sa.Column('mslp_hpa', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_name', 'observation_date', name='uq_historical_weather_location_date')
    )
    op.create_index(op.f('ix_historical_weather_readings_location_name'), 'historical_weather_readings', ['location_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historical_weather_readings_location_name'), table_name='historical_weather_readings')
    op.drop_table('historical_weather_readings')
    # ### end Alembic commands ###
