"""add gfs_forecast_points table

Revision ID: cbf59942506f
Revises: 8cf329ef2553
Create Date: 2026-09-08 07:04:21.627013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbf59942506f'
down_revision: Union[str, Sequence[str], None] = '8cf329ef2553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gfs_forecast_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.String(), nullable=False),
    sa.Column('run_hour', sa.String(), nullable=False),
    sa.Column('forecast_hour', sa.Integer(), nullable=False),
    sa.Column('valid_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('grid_latitude', sa.Float(), nullable=False),
    sa.Column('grid_longitude', sa.Float(), nullable=False),
    sa.Column('temp_2m_c', sa.Float(), nullable=True),
    sa.Column('relative_humidity_2m_pct', sa.Float(), nullable=True),
    sa.Column('wind_speed_10m_kmh', sa.Float(), nullable=True),
    sa.Column('wind_direction_10m_deg', sa.Float(), nullable=True),
    sa.Column('wind_gust_kmh', sa.Float(), nullable=True),
    sa.Column('precip_rate_mmh', sa.Float(), nullable=True),
    sa.Column('cape_j_per_kg', sa.Float(), nullable=True),
    sa.Column('cin_j_per_kg', sa.Float(), nullable=True),
    sa.Column('cloud_cover_pct', sa.Float(), nullable=True),
    sa.Column('mslp_hpa', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_date', 'run_hour', 'forecast_hour', 'grid_latitude', 'grid_longitude', name='uq_gfs_forecast_points_run_hour_point')
    )
    op.create_index(op.f('ix_gfs_forecast_points_grid_latitude'), 'gfs_forecast_points', ['grid_latitude'], unique=False)
    op.create_index(op.f('ix_gfs_forecast_points_grid_longitude'), 'gfs_forecast_points', ['grid_longitude'], unique=False)
    op.create_index(op.f('ix_gfs_forecast_points_run_date'), 'gfs_forecast_points', ['run_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gfs_forecast_points_run_date'), table_name='gfs_forecast_points')
    op.drop_index(op.f('ix_gfs_forecast_points_grid_longitude'), table_name='gfs_forecast_points')
    op.drop_index(op.f('ix_gfs_forecast_points_grid_latitude'), table_name='gfs_forecast_points')
    op.drop_table('gfs_forecast_points')
    # ### end Alembic commands ###
