"""create metar_readings table

Revision ID: f2c357533d96
Revises: e676a59533b5
Create Date: 2026-09-06 15:15:04.688937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2c357533d96'
down_revision: Union[str, Sequence[str], None] = 'e676a59533b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metar_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icao_id', sa.String(), nullable=False),
    sa.Column('raw_metar', sa.String(), nullable=False),
    sa.Column('observed_at', sa.String(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('dewpoint_c', sa.Float(), nullable=True),
    sa.Column('wind_dir_deg', sa.Float(), nullable=True),
    sa.Column('wind_speed_kt', sa.Float(), nullable=True),
    sa.Column('visibility_sm', sa.Float(), nullable=True),
    sa.Column('flight_category', sa.String(), nullable=True),
    sa.Column('station_name', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('icao_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metar_readings')
    # ### end Alembic commands ###
